title: Simulation robotique
author: Clément Besnier
execute:
  execute_notebooks: force
myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath

repository:
  url: https://github.com/clemsciences/slam-robot
  path_to_book: src/course
  branch: master
sphinx:
  config:
    language: fr
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  extra_footer: |
    <div>
    </div>